version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages: 
        pkg-manager: yarn
        cache-key: "yarn.lock"

  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.5-node
      - image: circleci/postgres:12.3
        # $ docker-compose run db postgres -V
        # postgres (PostgreSQL) 12.3 (Debian 12.3-1.pgdg100+1)
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_development
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout 
      - ruby/install-deps 
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build